import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,AppWindow,Images,FileText,ListChecks,Settings2,Download,ArrowUpRight,ArrowRight,ArrowLeft,Check,CheckCircle2,ChevronDown,ChevronRight,Copy,ExternalLink,FolderOpen,Sun,Moon,Smartphone,Monitor,Upload,Menu,X,Info,AlertCircle,Search,Package,CheckSquare,Square,RotateCcw,BookOpen} from 'lucide-react';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/inter/latin-700.css';
import '@fontsource/play/latin-700.css';
import {screens,fieldSpecs,initialWorkspace,suggestedSettings} from './data';
import sources from './sources.json';
import Benchmark from './Benchmark';
import './style.css';

const nav=[['overview','Overview',LayoutDashboard],['icons','Icon studio',AppWindow],['screenshots','Store artwork',Images],['copy','Listing copy',FileText],['benchmark','Competitor review',BookOpen],['checklist','Launch checklist',ListChecks],['settings','Store settings',Settings2],['downloads','Export center',Download]];
const iconUrl=(size=43.5,tone='light')=>`./assets/icon-${size}-${tone}.png`;
const shot=(platform,index)=>`./assets/${platform==='apple'?'ios':'android'}-${String(index+1).padStart(2,'0')}.png`;
const sourceMap=Object.fromEntries(sources.map(s=>[s.id,s]));
function Source({id,label}){let s=sourceMap[id];return s?<a className="source" href={s.url} target="_blank" rel="noreferrer">{label||'Official guidance'} <ArrowUpRight size={13}/></a>:null}
function Badge({children,type='neutral'}){return <span className={`badge ${type}`}>{children}</span>}
function IconImage({size=43.5,tone='light',className=''}){return <img className={`app-icon ${className}`} src={iconUrl(size,tone)} alt={`Openline icon with ${size}% mark coverage, ${tone} appearance`}/>}
function download(data,name,type='application/json'){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
const lengthOf=(value,unit)=>unit==='bytes'?new TextEncoder().encode(value).length:Array.from(value).length;
function Workspace(){
 const [ws,setWs]=useState(()=>structuredClone(initialWorkspace));
 const [view,setView]=useState('overview'),[platform,setPlatform]=useState('apple'),[dark,setDark]=useState(matchMedia('(prefers-color-scheme: dark)').matches),[mobileNav,setMobileNav]=useState(false);
 const [toast,setToast]=useState(''),[dirty,setDirty]=useState(false),[modal,setModal]=useState(null),[q,setQ]=useState(''),[taskPlatform,setTaskPlatform]=useState('All'),[taskStatus,setTaskStatus]=useState('All'),[tab,setTab]=useState('Home screen');
 const importRef=useRef();
 const done=ws.tasks.filter(t=>t.status==='done').length,blocked=ws.tasks.filter(t=>t.status==='blocked').length,percent=Math.round(done/ws.tasks.length*100);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer)},[toast]);
 useEffect(()=>{const f=e=>{if(e.key==='Escape'){setModal(null);setMobileNav(false)}};document.addEventListener('keydown',f);return()=>document.removeEventListener('keydown',f)},[]);
 useEffect(()=>{
  if(!modal)return;
  const previous=document.activeElement;
  const trap=e=>{
   if(e.key!=='Tab')return;
   const items=[...document.querySelectorAll('.modal button,.modal a[href],.modal textarea,.modal input,.modal select')].filter(el=>!el.disabled);
   const first=items[0],last=items[items.length-1];
   if(e.shiftKey&&(document.activeElement===first||!items.includes(document.activeElement))){e.preventDefault();last?.focus()}
   else if(!e.shiftKey&&(document.activeElement===last||!items.includes(document.activeElement))){e.preventDefault();first?.focus()}
  };
  document.addEventListener('keydown',trap);
  return()=>{document.removeEventListener('keydown',trap);if(previous?.isConnected)previous.focus()};
 },[modal]);
 useEffect(()=>{const f=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty]);
 function change(update){setWs(old=>({...old,...(typeof update==='function'?update(old):update),updatedAt:new Date().toISOString()}));setDirty(true)}
 function go(v){setView(v);setMobileNav(false);window.scrollTo({top:0,behavior:'instant'})}
 async function copy(text){try{await navigator.clipboard.writeText(text);setToast('Copied to clipboard')}catch{setModal({type:'text',text});setToast('Clipboard unavailable. Select and copy the text shown.')}}
 function save(){download(JSON.stringify(ws,null,2),'openline-launch-workspace.json');setDirty(false);setToast('Workspace exported. Keep this file to resume your progress.')}
 function importState(e){const file=e.target.files?.[0];if(!file)return;if(file.size>2e6){setToast('Choose a workspace JSON file smaller than 2 MB.');e.target.value='';return}
 file.text().then(text=>{const d=JSON.parse(text);
 if(![1,2].includes(d.schemaVersion)||![42.2,43.5,44.8,49.6,52.7,55.8,58,62,66,68].includes(d.iconSize)||!['light','dark'].includes(d.iconTone)||!Array.isArray(d.tasks)||d.tasks.length!==initialWorkspace.tasks.length||!Array.isArray(d.approvedScreens)||!d.approvedScreens.every(n=>Number.isInteger(n)&&n>=0&&n<6))throw Error('Invalid workspace');
 for(const p of ['apple','google'])for(const [key] of fieldSpecs[p])if(typeof d.copy?.[p]?.[key]!=='string'||d.copy[p][key].length>12000)throw Error('Invalid copy');
 const clean=structuredClone(initialWorkspace);clean.iconSize=[42.2,43.5,44.8,52.7].includes(d.iconSize)?d.iconSize:43.5;clean.iconTone=d.iconTone;clean.copy=d.copy;clean.approvedScreens=d.artworkRevision===2?d.approvedScreens:[];
 clean.tasks=initialWorkspace.tasks.map(t=>{const f=d.tasks.find(v=>v.id===t.id);if(!f||!['todo','review','blocked','done'].includes(f.status)||typeof f.notes!=='string'||typeof f.owner!=='string')throw Error('Invalid tasks');return {...t,status:f.status,notes:f.notes.slice(0,5000),owner:f.owner.slice(0,100)}});
 if(d.artworkRevision!==2)clean.tasks=clean.tasks.map(t=>['art','feature'].includes(t.id)&&t.status==='done'?{...t,status:'review',notes:t.notes+'\nArtwork changed in revision 02. Re-review required.'}:t);
 if(d.iconRevision!==3)clean.tasks=clean.tasks.map(t=>t.id==='icon'&&t.status==='done'?{...t,status:'review',notes:t.notes+'\nIcon resources changed in revision 03. Re-review required.'}:t);
 clean.settingsNotes=typeof d.settingsNotes==='string'?d.settingsNotes.slice(0,10000):'';setWs(clean);setDirty(false);setToast(d.artworkRevision!==2?'Workspace restored. Earlier artwork approvals were cleared because the compositions changed.':d.iconRevision!==3?'Workspace restored. The icon changed; review the new size and resources.':'Workspace restored from your file.');
 }).catch(()=>setToast('That is not a valid Openline workspace file. Nothing was changed.'));e.target.value=''}
 function patchTask(id,patch){change(old=>({tasks:old.tasks.map(t=>t.id===id?{...t,...patch}:t)}))}
 function exportCopy(){
 let md='# Openline store listing drafts\n\nReview against the native release build before submission. No credentials belong in this file.\n\n';
 for(const p of ['apple','google']){md+=`## ${p==='apple'?'Apple App Store':'Google Play'}\n\n`;for(const [key,label,max,unit]of fieldSpecs[p])md+=`### ${label}\n\n${ws.copy[p][key]}\n\n${lengthOf(ws.copy[p][key],unit)} / ${max} ${unit||'characters'}\n\n`}
 md+='\n## Official references\n\n'+sources.map(s=>`${s.title}: ${s.url}`).join('\n\n');
 download(md,'openline-store-copy.md','text/markdown');
 }
 function exportChecklist(){download('# Openline release checklist\n\nStatus is self-reported. Not an approval by Apple or Google.\n\n'+ws.tasks.map(t=>`- [${t.status==='done'?'x':' '}] ${t.title} (${t.platform}; ${t.requirement}; ${t.status})\n  Owner: ${t.owner}\n  ${t.detail}\n  Notes: ${t.notes||'None'}\n  Guidance: ${sourceMap[t.source]?.url}\n`).join('\n'),'openline-release-checklist.md','text/markdown')}
 const visibleTasks=ws.tasks.filter(t=>(taskPlatform==='All'||t.platform===taskPlatform||t.platform==='Both')&&(taskStatus==='All'||t.status===taskStatus)&&`${t.title} ${t.detail} ${t.group}`.toLowerCase().includes(q.toLowerCase()));
 const title={overview:'A considered launch, down to the icon.',icons:'A little less. A lot more Openline.',screenshots:'Tell the story, screen by screen.',copy:'The words that bring people in.',benchmark:'Learn from the category. Stay Openline.',checklist:'From prepared to ready to publish.',settings:'Set up the stores with confidence.',downloads:'Everything, in the right format.'}[view];
 const platformControl=<div className="segmented" aria-label="Store platform"><button className={platform==='apple'?'active':''} onClick={()=>setPlatform('apple')}>Apple App Store</button><button className={platform==='google'?'active':''} onClick={()=>setPlatform('google')}>Google Play</button></div>;
 return <>
 <a className="skip" href="#main">Skip to content</a>
 <input type="file" hidden accept=".json,application/json" ref={importRef} onChange={importState}/>
 {mobileNav&&<button className="nav-scrim" aria-label="Close menu" onClick={()=>setMobileNav(false)}/>}
 <aside className={`sidebar ${mobileNav?'open':''}`}>
  <a className="brand" href="#overview" onClick={e=>{e.preventDefault();go('overview')}}><img src="./assets/mark.png" alt="Openline"/><strong>Openline<span>Brand studio</span></strong></a>
  <div className="workspace-label">MOBILE APP LAUNCH <span>01</span></div>
  <nav aria-label="Main navigation">{nav.map(([id,label,Icon])=><button key={id} className={view===id?'nav-item active':'nav-item'} onClick={()=>go(id)}><Icon size={18}/><span>{label}</span>{id==='checklist'&&<small>{blocked}</small>}{view===id&&<ChevronRight size={15}/>}</button>)}</nav>
  <div className="side-bottom"><div className="mini-progress"><span>Release readiness</span><strong>{done}/{ws.tasks.length}</strong></div><div className="progress"><span style={{width:percent+'%'}}/></div><p>{blocked} items need evidence</p><button className="side-link" onClick={()=>setModal({type:'sources'})}><BookOpen size={16}/> Requirements & sources <ArrowUpRight size={14}/></button><div className="version"><span className="dot"/>Working draft · October 2026</div></div>
 </aside>
 <div className="shell">
 <header className="topbar"><div className="breadcrumb"><button className="icon-btn mobile-only" onClick={()=>setMobileNav(!mobileNav)} aria-label="Open navigation"><Menu size={20}/></button><span>Brand workspace</span><ChevronRight size={14}/><strong>{nav.find(n=>n[0]===view)[1]}</strong></div><div className="top-actions"><span className="save-state">{dirty?'Unsaved session changes':'Session workspace'}</span><button className="icon-btn" aria-label={dark?'Switch to light mode':'Switch to dark mode'} onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="btn small" onClick={save}><Download size={15}/> Save workspace</button></div></header>
 <main id="main">
 <div className="page-heading"><div><div className="eyebrow">OPENLINE / {view==='overview'?'LAUNCH WORKSPACE':nav.find(n=>n[0]===view)[1].toUpperCase()}</div><h1>{title}</h1><p>{view==='overview'?'One place for the app identity, store presentation, and the final steps before launch.':view==='icons'?'The original mark. More breathing room. Built for both home screens.':view==='screenshots'?'Six editorial compositions per store, built from your supplied mobile design sources.':view==='copy'?'Editable English drafts, live character limits, and no unverified performance claims.':view==='benchmark'?'A source-linked review of Saily, Airalo and Holafly, and what changed in our presentation.':view==='checklist'?'Evidence first. Mark an item complete only after it is verified in the native release.':view==='settings'?'A practical starting point, with recommendations kept separate from facts still to confirm.':'Download the production-format artwork and keep your review progress portable.'}</p></div>{view==='overview'?<button className="btn primary" onClick={()=>go('icons')}>Review the icon <ArrowRight size={16}/></button>:view==='screenshots'||view==='copy'?platformControl:null}</div>

 {view==='overview'&&<>
 <div className="overview-grid">
  <section className="identity-panel"><div className="panel-top"><span className="eyebrow">THE REFINED APP ICON</span><Badge type="green">Candidate 03</Badge></div><div className="icon-stage"><IconImage size={43.5}/><div className="measurement horizontal"><span>43.5% artwork width</span></div></div><div className="identity-bottom"><div><h2>More room. Same Openline.</h2><p>Another ~17.5% smaller than 52.7%. White square unchanged.</p></div><button className="arrow-btn" aria-label="Open icon studio" onClick={()=>go('icons')}><ArrowUpRight size={23}/></button></div></section>
  <section className="readiness-panel"><div className="panel-top"><span className="eyebrow">THE PATH TO LAUNCH</span><Badge type="amber">Not submission-ready</Badge></div><h2>Your creative is taking shape.<br/>Now, close the gaps.</h2><p>The assets are prepared for review. Native screenshots, privacy answers, and account details still need confirmation.</p><div className="readiness-number"><span>{percent}<small>%</small></span><div>{done} of {ws.tasks.length}<br/><span>checks verified by you</span></div></div><div className="progress"><span style={{width:percent+'%'}}/></div><div className="next-items">{[['Creative','Icon + 12 store compositions','Prepared for review'],['Compliance','Privacy, payments & account access','Needs evidence'],['Release','Signed builds & real-device QA','Still to do']].map(([a,b,c])=><div key={a}><span className="status-circle"/><div><strong>{a}</strong><small>{b}</small></div><span>{c}</span></div>)}</div><button className="btn full" onClick={()=>go('checklist')}>Open launch checklist <ArrowRight size={16}/></button></section>
 </div>
 <div className="section-heading"><div><h2>A first look at your store presence</h2><p>A connected visual story, from discovery to everyday use.</p></div><button className="text-btn" onClick={()=>go('screenshots')}>View all artwork <ArrowRight size={16}/></button></div>
 <div className="overview-shots">{screens.slice(0,4).map((s,i)=><button key={s.slug} onClick={()=>setModal({type:'image',src:shot('apple',i),title:s.title})}><img src={shot('apple',i)} alt={`${s.title} store artwork design reference`} loading="lazy"/><span><small>0{i+1}</small>{s.short}<ArrowUpRight size={16}/></span></button>)}</div>
 <div className="note"><Info size={18}/><p><strong>A launch kit, not a store submission.</strong> Artwork uses your supplied React design screens. Replace with verified native captures before publishing. Checklist and copy edits stay in this session; use Save workspace to keep them.</p></div>
 </>}

 {view==='icons'&&<>
 <div className="studio-grid"><section className="panel"><div className="panel-top"><h2>Icon canvas</h2><div className="segmented compact"><button className={ws.iconTone==='light'?'active':''} onClick={()=>change({iconTone:'light'})}>Default</button><button className={ws.iconTone==='dark'?'active':''} onClick={()=>change({iconTone:'dark'})}>Dark reference</button></div></div><div className="large-icon-stage"><div className="guide-box"><IconImage size={ws.iconSize} tone={ws.iconTone}/></div></div><div className="icon-meta"><span>1024 × 1024 master</span><span>White square unchanged</span></div><div className="size-options">{[42.2,43.5,44.8,52.7].map(n=><button key={n} className={ws.iconSize===n?'selected':''} onClick={()=>change({iconSize:n})}><strong>{n}%</strong><span>{n===43.5?'~17.5% smaller':n===52.7?'Previous':n===42.2?'~20% smaller':'~15% smaller'}</span>{ws.iconSize===n&&<Check size={15}/>}</button>)}</div><div className="panel-bottom"><p>Default: 43.5%, another ~17.5% reduction from 52.7%. Native ZIP uses this default; individual masters follow your selection.</p><a className="btn small" href={iconUrl(ws.iconSize,ws.iconTone)} download={`openline-${ws.iconSize}-${ws.iconTone}-1024.png`}><Download size={15}/> Download master</a></div></section>
 <section className="panel preview-panel"><div className="panel-top"><h2>In context</h2><div className="segmented compact">{['Home screen','Android masks'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div></div>{tab==='Home screen'?<div className="home-screen"><div className="phone-clock">9:41<span>●●● ▰</span></div><div className="home-date">Tuesday, October 6</div><div className="home-time">9:41</div><div className="home-icons"><div><span className="dummy-icon"><Images/></span><label>Photos</label></div><div><span className="dummy-icon"><Settings2/></span><label>Settings</label></div><div><IconImage size={ws.iconSize} tone={ws.iconTone}/><label>Openline</label></div><div><span className="dummy-icon"><FileText/></span><label>Notes</label></div></div><div className="home-dock"><span/><span/><span/><span/></div></div>:<div className="android-masks">{['circle','squircle','rounded'].map(m=><div key={m}><div className={`adaptive ${m}`}><img src="./assets/android-foreground.png" alt={`Android adaptive icon under ${m} mask`}/></div><span>{m}</span></div>)}<p>39.6dp adaptive mark on a 108dp canvas: 17.5% smaller than the previous 48dp. Below Android’s recommended range; native legibility testing is required.</p><div className="adaptive circle themed"><img src="./assets/android-monochrome.png" alt="Android monochrome themed icon"/></div></div>}<div className="preview-caption"><Smartphone size={16}/>{tab==='Home screen'?'Illustrative launcher preview, not an OS rendering.':'Mask simulations; a 48dp fallback is included in the kit.'}</div></section></div>
 <div className="comparison"><div><h2>The change is in the spacing.</h2><p>Same 64-pixel square. Another ~17.5% smaller inside it.</p></div><div className="compare-icons"><div><IconImage size={52.7}/><span>Before · 52.7%</span></div><ArrowRight size={18}/><div><IconImage size={43.5}/><span>Now · 43.5%</span></div></div></div>
 <div className="two-col"><section className="panel"><h2>Apple delivery</h2><p>Opaque PNG app catalog and a 1024px master. Separate layers are included for assembly in Icon Composer; they are not a compiled <code>.icon</code> document.</p><Source id="apple-icons"/><a className="btn full" href="./downloads/openline-native-icons.zip" download><Download size={16}/> Download native icon kit</a></section><section className="panel"><h2>Android delivery</h2><p>Legacy Android and Play listing icons use the new 43.5% mark. Adaptive and monochrome candidates also shrink by 17.5%, from 48dp to 39.6dp. This is below Android’s recommended 48–66dp range; a guideline-aligned 48dp fallback is preserved in the kit.</p><Source id="android-icons"/><div className="note small-note">Test small-size readability on devices before final approval. Apple dark and tinted PNGs remain appearance references.</div></section></div>
 </>}

 {view==='screenshots'&&<>
 <div className="note"><Info size={18}/><p><strong>Design references, not native release screenshots.</strong> These compositions use the supplied React UI. The export footer records that status. Native iOS and Android captures are required before final approval.</p></div>
 <div className="gallery-toolbar"><span>{platform==='apple'?'6 iPhone compositions · 1320 × 2868 · RGB PNG':'6 Android compositions · 1080 × 1920 · RGB PNG'}</span><Source id={platform==='apple'?'apple-screenshots':'google-assets'}/></div>
 <div className="gallery-grid">{screens.map((s,i)=><article className="shot-card" key={s.slug}><button className="shot-img" onClick={()=>setModal({type:'image',src:shot(platform,i),title:s.title})}><img src={shot(platform,i)} alt={`${s.title}. ${s.detail} Design-reference store artwork.`} loading="lazy"/><span><Images size={15}/> Preview</span></button><div className="shot-info"><small>0{i+1} / {s.short.toUpperCase()}</small><h3>{s.title}</h3><div className="shot-actions"><button className={ws.approvedScreens.includes(i)?'approved text-btn':'text-btn'} onClick={()=>change(old=>({approvedScreens:old.approvedScreens.includes(i)?old.approvedScreens.filter(n=>n!==i):[...old.approvedScreens,i]}))}>{ws.approvedScreens.includes(i)?<CheckSquare size={16}/>:<Square size={16}/>} Design {ws.approvedScreens.includes(i)?'approved':'review'}</button><a className="icon-btn" href={shot(platform,i)} download aria-label={`Download ${s.short}`}><Download size={17}/></a></div></div></article>)}</div>
 {platform==='google'&&<section className="feature-panel"><img src="./assets/google-feature.png" alt="Openline Google Play feature graphic design reference"/><div><Badge>1024 × 500 · RGB PNG</Badge><h2>The Play feature graphic</h2><p>A matching horizontal composition, with the same story and restrained branding.</p><a className="btn" href="./assets/google-feature.png" download><Download size={16}/> Download graphic</a></div></section>}
 <div className="section-heading"><div><h2>Preview the listing</h2><p>A visual approximation. Not a live store page or an endorsement.</p></div><button className="btn" onClick={()=>setModal({type:'store'})}>Open store preview <ArrowUpRight size={16}/></button></div><div className="two-col"><div className="panel"><h3>Native capture handoff</h3><p>Use the six artboards as the visual direction. Recapture implemented flows from the signed platform builds, confirm display sizes, and replace mock prices and data with approved samples.</p></div><div className="panel"><h3>iPad and tablet assets</h3><p>Not included because native tablet support is unconfirmed. Do not stretch phone screenshots into tablet slots. Resolve supported devices in the checklist.</p><button className="text-btn" onClick={()=>go('checklist')}>Review device support <ArrowRight size={15}/></button></div></div>
 </>}

 {view==='copy'&&<>
 <div className="copy-layout"><section className="copy-form"><div className="note"><Info size={18}/><p>English (US) draft. Verify against the shipped app. No “190+ countries”, “best signal”, activation-time or customer-count claims are assumed.</p></div>{fieldSpecs[platform].map(([key,label,max,unit])=>{const text=ws.copy[platform][key],len=lengthOf(text,unit),over=len>max;return <div className="copy-field" key={platform+key}><div><label htmlFor={`copy-${key}`}>{label}</label><span className={over?'over':'muted'}>{len.toLocaleString()} / {max.toLocaleString()} {unit||'characters'}</span><button className="icon-btn" aria-label={`Copy ${label}`} onClick={()=>copy(text)}><Copy size={16}/></button></div>{max<101?<input id={`copy-${key}`} aria-invalid={over} value={text} onChange={e=>change(old=>({copy:{...old.copy,[platform]:{...old.copy[platform],[key]:e.target.value}}}))}/>:<textarea id={`copy-${key}`} rows={max>1000?11:3} aria-invalid={over} value={text} onChange={e=>change(old=>({copy:{...old.copy,[platform]:{...old.copy[platform],[key]:e.target.value}}}))}/>} {over&&<p className="over">Over the field limit. Shorten this before submission.</p>}{key==='reviewNotes'&&<small>Preparation template only. Enter actual credentials securely in App Store Connect.</small>}</div>})}<button className="btn primary" onClick={exportCopy}><Download size={16}/> Export listing copy</button></section><aside className="copy-side panel"><Badge>LIVE TEXT PREVIEW</Badge><div className="listing-mini"><IconImage/><h2>{ws.copy[platform].name}</h2><p>{platform==='apple'?ws.copy.apple.subtitle:ws.copy.google.shortDescription}</p><span className="store-get">Get <small>Listing preview only</small></span></div><img className="mini-poster" src={shot(platform,0)} alt="First store composition"/><h3>Copy checklist</h3><ul><li>Names stay within 30 characters.</li><li>Apple keywords count UTF-8 bytes.</li><li>Every feature must exist in the release.</li><li>Confirm pricing and support details.</li><li>Review translations per locale.</li></ul><Source id={platform==='apple'?'apple-copy':'google-copy-build'}/></aside></div>
 </>}

 {view==='checklist'&&<>
 <div className="check-summary"><div><strong>{done}</strong><span>Verified</span></div><div><strong>{blocked}</strong><span>Need evidence</span></div><div><strong>{ws.tasks.filter(t=>t.status==='review').length}</strong><span>Ready for review</span></div><div className="check-progress"><div className="mini-progress"><span>Release readiness</span><b>{percent}%</b></div><div className="progress"><span style={{width:percent+'%'}}/></div></div></div>
 <div className="filterbar"><label className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a requirement..." aria-label="Search checklist"/></label><select aria-label="Filter by platform" value={taskPlatform} onChange={e=>setTaskPlatform(e.target.value)}>{['All','Apple','Google'].map(t=><option key={t}>{t}</option>)}</select><select aria-label="Filter by status" value={taskStatus} onChange={e=>setTaskStatus(e.target.value)}><option>All</option>{['todo','review','blocked','done'].map(t=><option key={t}>{t}</option>)}</select><button className="btn" onClick={exportChecklist}><Download size={16}/> Export</button></div>
 {!visibleTasks.length?<div className="empty"><Search size={32}/><h2>No matching checks</h2><p>Try a broader search or clear your filters.</p><button className="btn" onClick={()=>{setQ('');setTaskPlatform('All');setTaskStatus('All')}}>Clear filters</button></div>:<div className="task-list">{visibleTasks.map(t=><details key={t.id} className="task"><summary><button className={`task-check ${t.status==='done'?'checked':''}`} aria-label={`${t.status==='done'?'Reopen':'Complete'} ${t.title}`} onClick={e=>{e.preventDefault();patchTask(t.id,{status:t.status==='done'?'todo':'done'})}}>{t.status==='done'&&<Check size={15}/>}</button><div className="task-title"><strong>{t.title}</strong><span>{t.group} · {t.owner} · {t.requirement}</span></div><span className="platform-tag">{t.platform}</span><Badge type={t.status==='done'?'green':t.status==='blocked'?'amber':'neutral'}>{t.status==='done'?'Verified':t.status==='blocked'?'Needs evidence':t.status==='review'?'Review':'To do'}</Badge><ChevronDown size={16}/></summary><div className="task-detail"><p>{t.detail}</p><Source id={t.source}/><div className="task-inputs"><label>Owner<input value={t.owner} onChange={e=>patchTask(t.id,{owner:e.target.value})}/></label><label>Status<select value={t.status} onChange={e=>patchTask(t.id,{status:e.target.value})}><option value="todo">To do</option><option value="review">Ready for review</option><option value="blocked">Needs evidence</option><option value="done">Verified by owner</option></select></label></div><label>Evidence / notes<textarea placeholder="Record a test result or evidence reference. Never enter credentials or customer data." value={t.notes} onChange={e=>patchTask(t.id,{notes:e.target.value})} rows={3}/></label></div></details>)}</div>}
 <div className="note"><Info size={18}/><p>Progress is self-reported and session-only until exported. A checked box is not store approval. Save workspace to keep owners, notes, copy changes and statuses in a portable JSON file.</p></div>
 </>}

 {view==='settings'&&<>
 <div className="note"><AlertCircle size={18}/><p><strong>No console settings have been changed.</strong> These are suggested values and verified requirements, not declarations about Openline’s production app. Unknowns remain explicit.</p></div>
 {Array.from(new Set(suggestedSettings.map(s=>s.group))).map(group=><section className="settings-group" key={group}><h2>{group}</h2><div className="settings-table">{suggestedSettings.filter(s=>s.group===group).map(s=><article className="settings-row" key={s.field}><div><h3>{s.field}</h3><Source id={s.source}/></div><div><strong>{s.value}</strong><p>{s.detail}</p></div><Badge type={s.status==='Blocked'?'amber':s.status==='Requirement'?'green':'neutral'}>{s.status}</Badge></article>)}</div></section>)}
 <section className="panel"><h2>Decisions and handoff notes</h2><label className="muted" htmlFor="settings-notes">Record agreed settings, public URL references and owners. Do not enter credentials.</label><textarea id="settings-notes" rows={5} value={ws.settingsNotes} onChange={e=>change({settingsNotes:e.target.value})} placeholder="Publishing entity, confirmed bundle ID, device support, privacy/support/deletion URL decisions..."/></section>
 </>}

 {view==='benchmark'&&<Benchmark/>}
 {view==='downloads'&&<>
 <div className="download-hero"><Package size={36}/><div><Badge type="green">PREPARED FOR HANDOFF</Badge><h2>The complete launch resource kit</h2><p>Native icons, 12 store compositions, Play feature graphic, English copy, settings guidance and source-linked requirements. Design previews are labeled; no signed builds or compliance approvals are included.</p></div><a className="btn primary" href="./downloads/openline-launch-kit.zip" download><Download size={17}/> Download launch kit</a></div>
 <div className="download-list">{[
 ['Native icon package','Xcode catalog, Android resources, store masters and layer sources','./downloads/openline-native-icons.zip'],
 ['Store artwork package','6 iPhone + 6 Android PNGs, plus Play feature graphic. Design-reference status.','./downloads/openline-store-artwork.zip'],
 ['Requirements & handoff','Official requirements, unresolved decisions, technical integration notes','./downloads/store-requirements.md'],
 ['Competitor review','Saily, Airalo and Holafly: source-cited text and visual review, implemented improvements','./downloads/competitor-review.md']
 ].map(([title,description,href])=><a className="download-row" href={href} download key={title}><div className="file-icon"><FolderOpen size={22}/></div><div><h3>{title}</h3><p>{description}</p></div><Download size={20}/></a>)}</div>
 <div className="two-col"><section className="panel"><h2>Your working copy</h2><p>The launch kit is the prepared baseline. Export the workspace to preserve your current copy, checklist notes and decisions. Import that file when you return.</p><div className="inline-actions"><button className="btn primary" onClick={save}><Download size={16}/> Save workspace</button><button className="btn" onClick={()=>importRef.current.click()}><Upload size={16}/> Import workspace</button></div></section><section className="panel"><h2>Text-only handoff</h2><p>Download the current edits as readable Markdown for review or transfer into the store consoles. Actual review credentials stay out of this workspace.</p><div className="inline-actions"><button className="btn" onClick={exportCopy}><FileText size={16}/> Listing copy</button><button className="btn" onClick={exportChecklist}><ListChecks size={16}/> Checklist</button></div></section></div>
 <section className="panel"><div className="panel-top"><h2>Official guidance, not guesswork</h2><Badge>Checked 6 Oct 2026</Badge></div><div className="sources-grid">{sources.map(s=><a href={s.url} key={s.id} target="_blank" rel="noreferrer"><span>{s.title}</span><ArrowUpRight size={16}/></a>)}</div></section>
 </>}
 <footer><span>Openline Brand Studio</span><span>English launch draft · Requirements checked 6 October 2026</span><button onClick={()=>importRef.current.click()}>Import workspace <Upload size={13}/></button></footer>
 </main></div>
 {toast&&<div role="status" className="toast"><CheckCircle2 size={18}/>{toast}</div>}
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section className={`modal ${modal.type==='image'?'image-modal':''}`} role="dialog" aria-modal="true" aria-label={modal.title||'Preview'} onClick={e=>e.stopPropagation()}><button className="modal-close icon-btn" autoFocus aria-label="Close preview" onClick={()=>setModal(null)}><X size={22}/></button>
 {modal.type==='image'?<><h2>{modal.title}</h2><Badge type="amber">Design reference</Badge><img src={modal.src} alt={modal.title}/><a className="btn" href={modal.src} download><Download size={16}/> Download PNG</a></>:modal.type==='store'?<><Badge>STORE LISTING PREVIEW</Badge><div className="store-header"><IconImage/><div><h2>{ws.copy[platform].name}</h2><p>{platform==='apple'?ws.copy.apple.subtitle:ws.copy.google.shortDescription}</p><small>Openline · Travel</small></div></div><div className="store-screen-row">{screens.map((s,i)=><img src={shot(platform,i)} key={s.slug} alt={s.title}/>)}</div><h3>About this app</h3><p className="preline">{ws.copy[platform].description}</p><div className="note">No live store listing, ratings or download numbers are implied.</div></>:modal.type==='text'?<><h2>Copy text</h2><textarea rows={12} defaultValue={modal.text} onFocus={e=>e.target.select()}/></>:<><h2>Requirements & sources</h2><p>Verified against official documentation on 6 October 2026. Recheck policies before submission.</p>{sources.map(s=><div className="source-detail" key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} <ArrowUpRight size={16}/></a><p>{s.summary}</p></div>)}</>}</section></div>}
 </>;
}
createRoot(document.getElementById('root')).render(<Workspace/>);
