import React,{useState,useEffect,useRef} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check,Download,Expand,Info,Star,X} from 'lucide-react';
import config from './public/series.json';
import refs from './public/references/competitors.json';
import './store-preview.css';

const img=(id,p,n,full=false)=>`./series/${id}/${p==='apple'?'ios':'android'}-${String(n+1).padStart(2,'0')}.${full?'png':'webp'}`;
const brands=[{id:'openline',name:'Openline'},...refs.brands];
export default function StorePreview({ws,change,platform,setPlatform}){
 const [series,setSeries]=useState(ws.preferredSeries||'signal'),[mode,setMode]=useState('listing'),[brand,setBrand]=useState('openline'),[width,setWidth]=useState(390),[lightbox,setLightbox]=useState(null),[frame,setFrame]=useState(0);
 const dialog=useRef(),close=useRef(),returnFocus=useRef();
 const current=config.series.find(s=>s.id===series),preferred=config.series.find(s=>s.id===ws.preferredSeries);
 useEffect(()=>{if(ws.preferredSeries)setSeries(ws.preferredSeries)},[ws.preferredSeries]);
 useEffect(()=>{if(!lightbox)return;returnFocus.current=document.activeElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';close.current?.focus();const key=e=>{if(e.key==='Escape')setLightbox(null);if(e.key==='ArrowRight')setLightbox(v=>({...v,index:(v.index+1)%v.images.length}));if(e.key==='ArrowLeft')setLightbox(v=>({...v,index:(v.index+v.images.length-1)%v.images.length}));if(e.key==='Tab'){const items=[...dialog.current.querySelectorAll('button,a[href]')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);returnFocus.current?.focus()}},[!!lightbox]);
 function images(b,id=series){return b==='openline'?currentImages(id):refs.brands.find(r=>r.id===b)?.[platform]?.screenshots.map(s=>({src:s.src,full:s.src,title:`${brands.find(r=>r.id===b).name} · ${s.order}`,source:s.sourceUrl}))||[]}
 function currentImages(id){const s=config.series.find(r=>r.id===id);return s.heads.map((h,n)=>({src:img(id,platform,n),full:img(id,platform,n,true),title:h.join(' ')}))}
 function open(b,n,id=series){setLightbox({brand:b,index:n,images:images(b,id),name:b==='openline'?`Openline / ${config.series.find(s=>s.id===id).name}`:brands.find(r=>r.id===b).name})}
 function strip(b,id=series,large=false){return <div className={`sp-strip ${large?'large':''}`} aria-label={`${b==='openline'?config.series.find(s=>s.id===id).name:brands.find(r=>r.id===b).name} screenshot strip`}>{images(b,id).map((im,n)=><button className="sp-shot" key={im.src} onClick={()=>open(b,n,id)} aria-label={`Enlarge ${b} screenshot ${n+1}`}><img src={im.src} alt={im.title} loading="lazy"/><span>{String(n+1).padStart(2,'0')}<Expand size={13}/></span></button>)}</div>}
 function reference(b){const r=refs.brands.find(r=>r.id===b);return r?<a className="sp-source" href={r[platform].url} target="_blank" rel="noreferrer">Actual {platform==='apple'?'App Store':'Google Play'} listing <ArrowUpRight size={13}/></a>:<span className="sp-draft">Openline concept · Native captures pending</span>}
 function listing(b){
  const r=refs.brands.find(r=>r.id===b),own=b==='openline';
  return <div className={`sp-listing ${platform}`} style={{width}}>
   <div className="sp-status"><span>9:41</span><span>●●● ▰</span></div>
   <div className="sp-storebar"><ArrowLeft size={19}/><strong>{platform==='apple'?'App Store':'Google Play'}</strong><span>Preview</span></div>
   <div className="sp-appintro"><img src={own?'./assets/icon-43.5-light.png':r[platform].icon||r.icon} alt={`${own?'Openline':r.name} icon`}/><div>
    <h3>{own?ws.copy[platform].name:r[platform].title||r.name}</h3>
    <p>{own?(platform==='apple'?ws.copy.apple.subtitle:ws.copy.google.shortDescription):r.name}</p>
    <span className="sp-get" aria-label="Decorative store install button">{platform==='apple'?'GET':'Install'}</span>
   </div></div>
   <div className="sp-noratings">Listing simulation · Ratings & rankings omitted</div>
   <div className="sp-listing-shots">{images(b).map((im,n)=><button key={im.src} onClick={()=>open(b,n)} aria-label={`Enlarge ${b} screenshot ${n+1}`}><img src={im.src} alt={im.title}/></button>)}</div>
   <div className="sp-listing-description"><h3>{own?'Travel, with Openline.':'About this preview'}</h3><p>{own?ws.copy[platform].description:'Actual published screenshot artwork, shown in an approximate store layout. No competitor claims are adopted by Openline.'}</p>{reference(b)}</div>
  </div>
 }
 return <div className="sp-root">
  <div className="sp-brief"><div><span className="eyebrow">THREE ORANGE OPTIONS / ONE FINAL ICON</span><h2>The same Openline.<br/>Three shades of confidence.</h2><p>Your original orange direction, plus two new treatments. One stronger reason to choose us on screen 2. The rest stays simple, human and ready for travel.</p></div><div className="sp-decision"><img src="./assets/icon-43.5-light.png" alt="Approved Openline icon"/><div><strong>Icon locked. Orange retained.</strong><p>{preferred?`Shortlisted: ${preferred.name}`:'Choose between three orange treatments.'}</p><small>A shortlist is not submission approval.</small></div></div></div>
  <div className="sp-directions" aria-label="Screenshot directions">{config.series.map(s=><button key={s.id} className={`sp-direction ${series===s.id?'selected':''}`} aria-pressed={series===s.id} onClick={()=>{setSeries(s.id);setFrame(0)}}><div className="sp-direction-cover" style={{background:s.color}}><img src={img(s.id,platform,0)} alt={`${s.name} first screenshot`}/><span>{s.number}</span></div><div><strong>{s.name}{ws.preferredSeries===s.id&&<Star size={13}/>}</strong><small>{s.description}</small></div></button>)}</div>
  <div className="sp-controls"><div className="segmented">{[['listing','Store listing'],['compare','Compare brands'],['all','All three options']].map(([id,label])=><button key={id} className={mode===id?'active':''} aria-pressed={mode===id} onClick={()=>setMode(id)}>{label}</button>)}</div><div className="segmented"><button className={platform==='apple'?'active':''} onClick={()=>{setPlatform('apple');setFrame(0)}}>iPhone</button><button className={platform==='google'?'active':''} onClick={()=>{setPlatform('google');setFrame(0)}}>Android</button></div></div>
  <section className="sp-workbench">
   <div className="sp-workbench-title"><div><span className="eyebrow">DIRECTION {current.number}</span><h2>{current.name}</h2><p>{current.intent}</p></div><div className="sp-actions"><button className="btn small" onClick={()=>change({preferredSeries:ws.preferredSeries===series?null:series})}>{ws.preferredSeries===series?<Check size={15}/>:<Star size={15}/>} {ws.preferredSeries===series?'Shortlisted · clear':'Shortlist direction'}</button><a className="btn small" href={`./downloads/openline-series-${series}.zip`} download><Download size={15}/> Series ZIP</a></div></div>
   {mode==='listing'&&<>
    <div className="sp-subcontrols"><div className="sp-brandtabs">{brands.map(b=><button key={b.id} onClick={()=>setBrand(b.id)} className={brand===b.id?'active':''} aria-pressed={brand===b.id}>{b.name}</button>)}</div><label className="sp-width">Preview width <select aria-label="Listing preview width" value={width} onChange={e=>setWidth(Number(e.target.value))}><option value={375}>375 px</option><option value={390}>390 px</option><option value={430}>430 px</option></select></label></div>
    <div className="sp-listing-stage">{listing(brand)}<aside className="sp-listing-notes"><span className="eyebrow">THE FIRST IMPRESSION</span><h3>{brand==='openline'?current.heads[0].join(' '):brands.find(b=>b.id===brand).name}</h3><p>{brand==='openline'?current.description:'These are the actual public listing graphics, not re-creations. Use the tabs to see each brand in the same preview shell.'}</p><ol><li>Read the first headline at listing size.</li><li>Swipe the strip to follow all six screens.</li><li>Open a frame to inspect its full composition.</li></ol><div className="sp-smallnote">The store shell is illustrative, not a pixel-exact OS capture. {platform==='apple'?'1320 × 2868':'1080 × 1920'} Openline exports are available at full resolution.</div>{reference(brand)}<a className="text-btn" href="./downloads/openline-final-icon-all-formats.zip" download>Download the approved icon <ArrowRight size={15}/></a></aside></div>
    <div className="sp-sequence-heading"><h3>Complete six-screen sequence</h3><span>Scroll horizontally · click to enlarge</span></div>{strip(brand,series,true)}
   </>}
   {mode==='compare'&&<>
    <div className="sp-compare-intro"><p>Four brands. The same display width. Different stories.</p><label>Compare frame <select aria-label="Comparison frame" value={frame} onChange={e=>setFrame(Number(e.target.value))}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n+1} of 6</option>)}</select></label></div>
    <div className="sp-comparison">{brands.map(b=><article key={b.id}><div className="sp-compare-brand"><strong>{b.name}</strong><small>{b.id==='openline'?current.name:'Published reference'}</small></div><button className="sp-compare-image" onClick={()=>open(b.id,frame)} aria-label={`Enlarge ${b.id} comparison frame ${frame+1}`}><img src={images(b.id)[frame]?.src} alt={`${b.name} screenshot ${frame+1}`}/></button>{reference(b.id)}</article>)}</div>
    <div className="sp-reference-sequences">{brands.map(b=><section key={b.id}><div className="sp-sequence-heading"><h3>{b.name} / full sequence</h3>{reference(b.id)}</div>{strip(b.id)}</section>)}</div>
   </>}
   {mode==='all'&&<div className="sp-all-series">{config.series.map(s=><section key={s.id}><div className="sp-sequence-heading"><div><span className="eyebrow">{s.number}</span><h3>{s.name}</h3><p>{s.description}</p></div><button className="btn small" onClick={()=>{setSeries(s.id);setMode('listing');setBrand('openline')}}>Preview this series <ArrowRight size={14}/></button></div>{strip('openline',s.id)}<a className="sp-source" href={`./downloads/openline-series-${s.id}.zip`} download>Download {s.name}: 6 iPhone + 6 Android PNGs <Download size={13}/></a></section>)}</div>}
  </section>
  <div className="sp-bottom"><section className="panel"><h3>What works? What needs changing?</h3><p>Review notes and the shortlisted direction are included in Save workspace. They are not uploaded or saved to a shared server.</p><textarea aria-label="Screenshot review notes" placeholder="For example: keep Original orange, but use Airy orange's upright phone…" value={ws.screenshotNotes||''} maxLength={10000} onChange={e=>change({screenshotNotes:e.target.value})}/><small>{preferred?`${preferred.name} is shortlisted for discussion. No series is approved for submission.`:'No series selected. Compare the three orange treatments.'}</small></section><section className="panel"><h3>The orange review bundle</h3><p>All three orange options, both phone formats, editable sources and the one-paragraph positioning. Competitor assets are excluded from every Openline download.</p><a className="btn full" href="./downloads/openline-orange-series.zip" download><Download size={16}/> Download all three options</a><a className="btn full" href="./downloads/openline-orange-series-sources.zip" download><Download size={16}/> Editable sources</a></section></div>
  <div className="note"><Info size={19}/><p><strong>Creative options, not upload-ready store screenshots.</strong> Openline images use the supplied React design screens, with sample data. Verify native captures and the launch network-partner evidence before submission. No cheapest, automatic-switching or universal multi-network-access claim is made. Your final 43.5% icon remains unchanged. <a className="sp-source" href="./downloads/positioning-claims.md" download>Positioning & claim boundaries</a></p></div>
  <details className="sp-attribution"><summary>Competitor sources & image attribution</summary><p>{refs.attribution} {refs.disclaimer} Checked {refs.checkedAt}. Google references are lower-resolution source images; full-size inspection cannot add detail.</p>{refs.brands.map(b=><div key={b.id}><strong>{b.name}</strong> · <a href={b.apple.url} target="_blank" rel="noreferrer">App Store</a> · <a href={b.google.url} target="_blank" rel="noreferrer">Google Play</a></div>)}</details>
  {lightbox&&<div className="sp-lightbox" onClick={e=>{if(e.target===e.currentTarget)setLightbox(null)}}><div className="sp-lightbox-dialog" role="dialog" aria-modal="true" aria-label={`${lightbox.name} full screenshot preview`} ref={dialog}><div className="sp-lightbox-bar"><div><strong>{lightbox.name}</strong><span>{lightbox.index+1} / {lightbox.images.length} · {platform==='apple'?'iPhone':'Android'}</span></div><button ref={close} className="icon-btn" aria-label="Close full screenshot preview" onClick={()=>setLightbox(null)}><X/></button></div><div className="sp-lightbox-image"><img src={lightbox.images[lightbox.index].full} alt={lightbox.images[lightbox.index].title}/></div><div className="sp-lightbox-footer"><button className="btn small" onClick={()=>setLightbox(v=>({...v,index:(v.index+v.images.length-1)%v.images.length}))}><ArrowLeft size={16}/>Previous</button>{lightbox.brand==='openline'?<a className="btn small" href={lightbox.images[lightbox.index].full} download><Download size={16}/> Full PNG</a>:<a className="btn small" href={lightbox.images[lightbox.index].source} target="_blank" rel="noreferrer">Original image <ArrowUpRight size={16}/></a>}<button className="btn small" onClick={()=>setLightbox(v=>({...v,index:(v.index+1)%v.images.length}))}>Next<ArrowRight size={16}/></button></div></div></div>}
 </div>
}
